site_name: gf-vue-admin在线文档
site_author: 'SliverHorn'
repo_name: 'gf-vue-admin-doc'
repo_url: 'https://github.com/SliverHorn/gf-vue-admin-doc'
site_url: 'https://sliverhorn.github.io/'

copyright: 'Copyright &copy; 2020 - 2020 SliverHorn'

# Configuration, https://gitlab.com/lramage/mkdocs-gitbook-theme
theme:
#  name: 'rtd-dropdown'
  name: 'cluster'

nav:
- 简介: 'index.md'
- 介绍: 'Introduction/index.md'
- 小白说明书: 'Manual/index.md'
- 目录结构: 'Manual/directory.md'
- 配置文件: 'Manual/config.md'
- JWT详解: 'jwt/index.md'
- JWT详解(ENGLISH): 'jwt/english.md'
- About: 'about/index.md'


extra:
  social:
    - type: 'github'
      link: 'https://github.com/SliverHorn'